# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('mailid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('candidate', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=150)),
            ],
        ),
    ]
